### ISSUE TITLE
Buckets is null

### ISSUE THREAD

**Issue by FanbaTheCoolio** [Waqax19/Programming#1]
it no work aaaaaaaaaaaaaaa

**Comment by Waqax19** [comment]
try it please

**Comment by FanbaTheCoolio** [comment]
oki doki

**Comment by Waqax19** [comment]
best of luck :D

**Comment by FanbaTheCoolio** [comment]
thank :)

**Comment by FanbaTheCoolio** [comment]
buckets is null for some reason so i know what to start with now :D

> best of luck :D
